

To position the mouse cursor at the browser tab 

Press Ctrl + 1 
through Ctrl + 8 to switch to the corresponding tab. 

more than eight tabs open, 
Ctrl + 9 to switch to the last tab.

Ctrl + Tab to cycle through tabs.



Browser navigation involves moving between different web pages or
 websites within a web browser. 


move the mouse cursor to the browser's address bar 
Press F6 or
Ctrl + L


Backward Navigation:
Backspace or Alt + Left Arrow



Forward Navigation:
Press Alt + Right Arrow


Reload/Refresh Page:
Press F5 or
Ctrl + R


Open New Tab:
Press Ctrl + T


Close Current Tab:
Press Ctrl + W

Switch Between Tabs:
Press Ctrl + Tab 
to move to the next tab. 
Press Ctrl + Shift + Tab to move to the previous tab.

Open Address Bar:
Press Ctrl + L or F6


Go to Home Page:
Press Alt + Home