



Close the Active Window:

Press Alt + F4 while the window is active.
Close the Active Application:

Ctrl + W while the application window is active. 
Note that this shortcut works in many, but not all, applications.

Preview and Switch Between Windows:

Keyboard Shortcut: Press Alt + Tab



To open a new instance of an application in Windows, you can use the following methods:

Keyboard Shortcut: Hold down the Shift key and then click on the application icon on the taskbar.



To minimize an application in Windows, you can use the following methods:

Keyboard Shortcut: Press Windows key + Down Arrow