
Close the Active Window:
Alt + F4 

Ctrl + W 


Preview and Switch Between Windows:
Alt + Tab



open a new instance of an application in Windows, 
Shift key and then click on the application icon on the taskbar.


minimize an application in Windows, 
Windows key + Down Arrow

maximize windows 
WIN-KEY + Up Arrow

Task View 
WiN-KEY + Tab

Swith Open Apps
WIN_KEY + D

Shut Down 
WIN_KEY + X

LOCK 
WIN_KEy + L


open new instance of an app
WIN + SHIFT + NUMBER
