Ctrl +O

Open a previously saved note
2. Ctrl + S

Save/Save As
3. Ctrl + N

Open a New Blank Page
4. Ctrl + P

Open Print
5. Ctrl + Z

Undo
6. Ctrl + X

Cut
7. Ctrl + V

Paste
8. Ctrl + C

Copy
9. Ctrl + F

Open Find


Ctrl + H

Open Replace


[intemediate]
11. Ctrl + A
Select All


12. F5 or Fn + F5
Insert the Date and Time

13 open clibboard
windows  key + V

"link" = "https://www.instructables.com/Keyboard-Shortcuts-for-Notepad/"