Press this key

To do this

Ctrl + X

Cut the selected item.

Ctrl + C (or Ctrl + Insert)

Copy the selected item.

Ctrl + V (or Shift + Insert)

Paste the selected item.

Ctrl + Z

Undo an action.

Alt + Tab

Switch between open apps.

Alt + F4

Close the active item, or exit the active app.

Windows logo key  + L

Lock your PC.

Windows logo key  + D

Display and hide the desktop.

F2

Rename the selected item.

F3

Search for a file or folder in File Explorer.

F4

Display the address bar list in File Explorer.

F5

Refresh the active window.

F6

Cycle through screen elements in a window or on the desktop.

F10

Activate the Menu bar in the active app.

Alt + F8

Show your password on the sign-in screen.

Alt + Esc

Cycle through items in the order in which they were opened.

Alt + underlined letter

Perform the command for that letter.

Alt + Enter

Display properties for the selected item.

Alt + Spacebar

Open the shortcut menu for the active window.

Alt + Left arrow

Go back.

Alt + Right arrow

Go forward.

Alt + Page Up

Move up one screen.

Alt + Page Down

Move down one screen.

Ctrl + F4

Close the active document (in apps that are full-screen and let you have multiple documents open at the same time).

Ctrl + A

Select all items in a document or window.

Ctrl + D (or Delete)

Delete the selected item and move it to the Recycle Bin.

Ctrl + R (or F5)

Refresh the active window.

Ctrl + Y

Redo an action.

Ctrl + Right arrow

Move the cursor to the beginning of the next word.

Ctrl + Left arrow

Move the cursor to the beginning of the previous word.

Ctrl + Down arrow

Move the cursor to the beginning of the next paragraph.

Ctrl + Up arrow

Move the cursor to the beginning of the previous paragraph.

Ctrl + Alt + Tab

Use the arrow keys to switch between all open apps.

Alt + Shift + arrow keys

When a group or tile is in focus on the Start menu, move it in the direction specified.

Ctrl + Shift + arrow keys

When a tile is in focus on the Start menu, move it into another tile to create a folder.

Ctrl + arrow keys

Resize the Start menu when it's open.

Ctrl + arrow key (to move to an item) + Spacebar

Select multiple individual items in a window or on the desktop.

Ctrl + Shift with an arrow key

Select a block of text.

Ctrl + Esc

Open Start.

Ctrl + Shift + Esc

Open Task Manager.

Ctrl + Shift

Switch the keyboard layout when multiple keyboard layouts are available.

Ctrl + Spacebar

Turn the Chinese input method editor (IME) on or off.

Shift + F10

Display the shortcut menu for the selected item.

Shift with any arrow key

Select more than one item in a window or on the desktop, or select text in a document.

Shift + Delete

Delete the selected item without moving it to the Recycle Bin first.

Right arrow

Open the next menu to the right, or open a submenu.

Left arrow

Open the next menu to the left, or close a submenu.

Esc

Stop or leave the current task.

PrtScn

Take a screenshot of your whole screen and copy it to the clipboard. 

Note: You can change this shortcut so it also opens  screen snipping, which lets you edit your screenshot. Select Start  > Settings > Ease of Access > Keyboard, and turn on the toggle under Print Screen shortcut.

Use PrtSc