

Shift + click a taskbar button

Open an app or quickly open another instance of an app.

Ctrl + Shift + click a taskbar button

Open an app as an administrator.

Shift + right-click a taskbar button

Show the window menu for the app.

Shift + right-click a grouped taskbar button

Show the window menu for the group.

Ctrl + click a grouped taskbar button

Cycle through the windows of the group.