
Windows logo key 

Open or close Start.

Windows logo key  + A

Open Quick Settings. Updated in Windows 11.

Windows logo key  + B

Set focus to the first icon in the Taskbar corner.

Windows logo key  + C

Open Windows Copilot. Updated in Windows 11.

Windows logo key  + Shift + C

Open the charms menu.

Windows logo key  + Ctrl + C

Turn on color filters (enable this shortcut first in Color Filter settings).

Windows logo key  + D

Display and hide the desktop.

Windows logo key  + E

Open File Explorer.

Windows logo key  + F

Open Feedback Hub and take a screenshot.

Windows logo key  + G

Open Xbox Game Bar when a game is open.

Windows logo key  + Alt + B

Turn HDR on or off.Note: Applies to the Xbox Game Bar app version 5.721.7292.0 or newer. To update your Xbox Game Bar, go to the Microsoft Store app and check for updates.

Windows logo key  + H

Launch voice typing. Updated in Windows 11.

Windows logo key  + I

Open Settings.

Windows logo key  + J

Set focus to a Windows tip when one is available.When a Windows tip appears, bring focus to the Tip.  Pressing the keyboard shortcuts again to bring focus to the element on the screen to which the Windows tip is anchored.

Windows logo key  + K

Open Cast from Quick Settings. Updated in Windows 11.

Windows logo key  + Alt + K

Toggle microphone mute in apps that support Call Mute. Available starting in Windows 11, version 22H2.

Windows logo key  + L

Lock your PC or switch accounts.

Windows logo key  + M

Minimize all windows.

Windows logo key  + Shift + M

Restore minimized windows on the desktop.

Windows logo key  + N

Open notification center and calendar. Updated in Windows 11.

Windows logo key  + O

Lock device orientation.

Windows logo key  + P

Choose a presentation display mode.

Windows logo key  + Ctrl + Q

Open Quick Assist.

Windows logo key  + R

Open the Run dialog box.

Windows logo key  + Alt + R

Record video of game window in focus (using Xbox Game Bar).

Windows logo key  + S

Open search.

Windows logo key  + Shift + S

Take a screenshot of part of your screen.

Windows logo key  + T

Cycle through apps on the taskbar.

Windows logo key  + U

Open Accessibility Settings.

Windows logo key  + V

Open the clipboard history.Note: Clipboard history isn't turned on by default. If you'd like to turn it on, use this keyboard shortcut and then select the prompt to turn on history. Or you can select Start  > Settings  > System  > Clipboard , and set Clipboard history to On.

Windows logo key  + Shift + V

Set focus to a notification.

Windows logo key  + W

Open Widgets. Updated in Windows 11.

Windows logo key  + X

Open the Quick Link menu.

Windows logo key  + Y

Switch input between Windows Mixed Reality and your desktop.

Windows logo key  + Z

Open the snap layouts. Updated in Windows 11.

Windows logo key  + period (.) or semicolon (;)

Open emoji panel.

Windows logo key  + comma (,)

Temporarily peek at the desktop.

Windows logo key  + Pause

Opens Start  > Settings  > System  > About .

Windows logo key  + Ctrl + F

Search for PCs (if you're on a network).

Windows logo key  + number

Open the desktop and start the app pinned to the taskbar in the position indicated by the number. If the app is already running, switch to that app.

Windows logo key  + Shift + number

Open the desktop and start a new instance of the app pinned to the taskbar in the position indicated by the number.

Windows logo key  + Ctrl + number

Open the desktop and switch to the last active window of the app pinned to the taskbar in the position indicated by the number.

Windows logo key  + Alt + number

Open the desktop and open the Jump List for the app pinned to the taskbar in the position indicated by the number.

Windows logo key  + Ctrl + Shift + number

Open the desktop and open a new instance of the app located at the given position on the taskbar as an administrator.

Windows logo key  + Tab

Open Task view.

Windows logo key  + Up arrow

Maximize the window.

Windows logo key  + Alt + Up arrow

Snap window in focus to top half of screen. New with Windows 11.

Windows logo key  + Down arrow

Remove current app from screen or minimize the desktop window.

Windows logo key  + Alt + Down arrow

Snap window in focus to bottom half of screen. New with Windows 11.

Windows logo key  + Left arrow

Maximize the app or desktop window to the left side of the screen.

Windows logo key  + Right arrow

Maximize the app or desktop window to the right side of the screen.

Windows logo key  + Home

Minimize all except the active desktop window (restores all windows on second stroke).

Windows logo key  + Shift + Up arrow

Stretch the desktop window to the top and bottom of the screen.

Windows logo key  + Shift + Down arrow

Restore/minimize active desktop windows vertically, maintaining width.

Windows logo key  + Shift + Left arrow or Right arrow

Move an app or window in the desktop from one monitor to another.

Windows logo key  + Shift + Spacebar

Cycle backwards through language and keyboard layout.

Windows logo key  + Spacebar

Switch input language and keyboard layout.

Windows logo key  + Ctrl + Spacebar

Change to a previously selected input.

Windows logo key  + Ctrl + Enter

Turn on Narrator.

Windows logo key  + Plus (+)

Open Magnifier and zoom in.

Windows logo key  + Minus (-)

Zoom out in Magnifier.

Windows logo key  + Esc

Close Magnifier.

Windows logo key  + forward slash (/)

Begin IME reconversion.

Windows logo key  + Ctrl + Shift + B

Wake PC from blank or black screen.

Windows logo key  + PrtScn

Save full screen screenshot to file.

Windows logo key  + Alt + PrtScn

Save screenshot of game window in focus to file (using Xbox Game Bar).

Windows logo key  + Alt + Enter (on taskbar item focus)

Open taskbar settings.