
["Hyperlink and Printing:"]

"Insert hyperlink for the selected text." = "Ctrl + K"
"Print the current page or document." = "Ctrl + P"


["Cursor Movement"]
"Go to the beginning of the current line" = "Home"
"Go to the beginning of the document" = "Ctrl + Home"
"Go to the end of the current line" = "End"
"Go to the end of the document" = "Ctrl + End"
"Highlight from the current position to the beginning of the line" = "Shift + Home"
"Highlight from the current position to the end of the line" = "Shift + End"
"Move one word to the left at a time" = "Ctrl + ←"
"Move one word to the right at a time" = "Ctrl + →"

["Undo and Redo"]
"Redo the last action" = "Ctrl + Y"
"Undo the last action" = "Ctrl + Z"



["Text Editing"]
"Select all text" = "Ctrl + A"
"Change the selected text to bold or remove bold" = "Ctrl + B"
"Change the selected text to italics or remove italics" = "Ctrl + I"
"Change selected text to underlined or remove underline" = "Ctrl + U"
"Open the find window for the current document, web page, or window" = "Ctrl + F"
"Save the current document file" = "Ctrl + S"
"Cut the selected item" = "Ctrl + X or Shift + Del"
"Copy the selected item" = "Ctrl + C or Ctrl + Ins"
"Paste" = "Ctrl + V or Shift + Insert"
"Insert hyperlink for the selected text" = "Ctrl + K"
"Print the current page or document" = "Ctrl + P"

["System and Program Management"]
"Open the Start menu" = "Ctrl + Esc"
"Open Windows Task Manager" = "Ctrl + Shift + Esc"
"Close the currently active program" = "Alt + F4"
"Open the properties for the selected item (file, folder, shortcut, etc.)" = "Alt + Enter"

["Windows"]
"Lock the computer, requiring password entry to access again" = "Windows key + L"
"Access the Power User Tasks Menu in Windows 8 and Windows 10" = "Windows key + X"
"Minimize the active program window" = "Windows key + ↓"
"Maximize the active program window" = "Windows key + ↑"


["General"]
"Copy" = "Ctrl + C"
"Cut" = "Ctrl + X"
"Paste" = "Ctrl + V"
"Undo" = "Ctrl + Z"
"Redo" = "Ctrl + Y"
"Select All" = "Ctrl + A"
"Save" = "Ctrl + S"


["File Explorer"]
"Open File Explorer" = "Win + E"
"Focus on address bar" = "Alt + D"
"Create a new folder" = "Ctrl + Shift + N"

["Taskbar"]
"Open or switch to the corresponding taskbar app" = "Win + 1, 2, 3, etc."
"Cycle through taskbar apps" = "Win + T"
"Show desktop, minimize, or restore all windows" = "Win + D"

["System"]
"Lock the computer" = "Win + L"
"Open Task Manager" = "Ctrl + Shift + Esc"
"Close the active window or application" = "Alt + F4"


["Virtual Desktop"]
"Create a new virtual desktop" = "Ctrl + Win + D"
"Switch between virtual desktops" = "Ctrl + Win + Left/Right Arrow"




