["Keys	Description"]


"File menu options in the current program" = "Alt + F"
"Open Edit options in the current program" = "Alt + E"
"Switch between open programs" = "Alt + Tab"
"View help information (F1 is used by almost every Windows program to display help)" = "F1"
"Rename a selected file" = "F2"
"Refresh the current program window" = "F5"
"Bookmark the current page in most Internet browsers" = "Ctrl + D"
"Create a new or blank document in some software or open a new tab in most Internet browsers" = "Ctrl + N"
"Open a file in the current software" = "Ctrl + O"
"Select all text" = "Ctrl + A"
"Change the selected text to bold or remove bold" = "Ctrl + B"
"Change the selected text to italics or remove italics" = "Ctrl + I"
"Change selected text to underlined or remove underline" = "Ctrl + U"
"Open the find window for the current document, web page, or window" = "Ctrl + F"
"Save the current document file" = "Ctrl + S"
"Cut the selected item" = "Ctrl + X or Shift + Del"
"Copy the selected item" = "Ctrl + C or Ctrl + Ins"
"Paste" = "Ctrl + V or Shift + Insert"
"Redo the last action" = "Ctrl + Y"
"Undo the last action" = "Ctrl + Z"
"Insert hyperlink for the selected text" = "Ctrl + K"
"Print the current page or document" = "Ctrl + P"
"Go to the beginning of the current line" = "Home"
"Go to the beginning of the document" = "Ctrl + Home"
"Go to the end of the current line" = "End"
"Go to the end of the document" = "Ctrl + End"
"Highlight from the current position to the beginning of the line" = "Shift + Home"
"Highlight from the current position to the end of the line" = "Shift + End"
"Move one word to the left at a time" = "Ctrl + ←"
"Move one word to the right at a time" = "Ctrl + →"
"Open the Start menu" = "Ctrl + Esc"
"Open Windows Task Manager" = "Ctrl + Shift + Esc"
"Close the currently active program" = "Alt + F4"
"Open the properties for the selected item (file, folder, shortcut, etc.)" = "Alt + Enter"
"Lock the computer, requiring password entry to access again" = "Windows key + L"
"Access the Power User Tasks Menu in Windows 8 and Windows 10" = "Windows key + X"
"Minimize the active program window" = "Windows key + ↓"
"Maximize the active program window" = "Windows key + ↑"
